CREATE TABLE PATIENTS_BED(
	
	PATIENTS_BED_ID 	NUMBER(9) NOT NULL DEFAULT NEXTVAL('SEQ_PATIENT_BED_ID'),
	TOTAL_BEDS			NUMBER(9) NOT NULL,
	CONSTRAINT PATIENTS_BED_ID_PK PRIMARY KEY(PATIENTS_BED_ID)
);

CREATE SEQUENCE SEQ_PATIENT_BED_ID MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 100;